M48
; DRILL file KiCad 10.0.1 date 2026-09-04T01:23:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-04T01:23:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X75.0Y-30.0
X75.0Y-84.0
X90.0Y-30.0
X90.0Y-84.0
T2
X135.0Y-30.0
X135.0Y-84.0
M30
